config/routes.rb
Rails.application.routes.draw do
  resources :characters do
    resources :tasks
    resources :results
  end
  root "characters#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
  validates :name, presence: true
  validates :personality, presence: true
  validates :image_src, presence: true

  has_many :tasks, dependent: :destroy
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :character
  has_many :results, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: %i[ show edit update destroy ]

  # GET /characters or /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1 or /characters/1.json
  def show
    @tasks = @character.tasks.order(created_at: :desc).limit(3)
    @results = @tasks.map(&:results).flatten.sort_by(&:created_at).reverse.take(3)
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters or /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to character_url(@character), notice: "Character was successfully created." }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1 or /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to character_url(@character), notice: "Character was successfully updated." }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1 or /characters/1.json
  def destroy
    @character.destroy!

    respond_to do |format|
      format.html { redirect_to characters_url, notice: "Character was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def character_params
      params.require(:character).permit(:name, :personality, :image_src)
    end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: %i[show edit update destroy]

  # GET /results or /results.json
  def index
    @character = Character.find(params[:character_id])
    @tasks = @character.tasks.order(created_at: :desc)
    @results = @tasks.map(&:results).flatten.sort_by(&:created_at).reverse
  end

  # GET /results/1 or /results/1.json
  def show
    logger.debug @result
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit; end

  # POST /results or /results.json
  def create
    @task = Task.find(params[:task_id])
    @character = Character.find(params[:character_id])

    client = OpenAI::Client.new

    content = "#{@character.personality} - based on this personality, complete this task, split every line with '\n' - #{@task.description}"

    response = client.chat(
      parameters: {
        model: 'gpt-4',
        messages: [{ role: 'user', content: }],
        temperature: 0.7
      }
    )

    content = response.dig('choices', 0, 'message', 'content')
    image_response = client.images.generate(parameters: {
                                              prompt: "A thumbnail for - #{@task.description}", model: 'dall-e-3', size: '1024x1024', quality: 'standard'
                                            })

    image_src = image_response.dig('data', 0, 'url')

    @result = @task.results.build(content:, image_src:)

    respond_to do |format|
      if @result.save
        format.html do
          redirect_to character_result_path(@character, @result), notice: 'Result was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1 or /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html do
          redirect_to character_result_path(@character, @result), notice: 'Result was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1 or /results/1.json
  def destroy
    @result.destroy!

    respond_to do |format|
      format.html { redirect_to character_results_path(@character), notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_result
    @result = Result.find(params[:id])
    @character = Character.find(params[:character_id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]
  before_action :set_character
  # GET /tasks or /tasks.json
  def index
    @character = Character.find(params[:character_id])
    @tasks = @character.tasks.order(created_at: :desc)
  end

  # GET /tasks/1 or /tasks/1.json
  def show; end

  # GET /tasks/new
  def new
    @task = @character.tasks.build
  end

  # GET /tasks/1/edit
  def edit; end

  # POST /tasks or /tasks.json
  def create
    @task = @character.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to character_task_path(@character, @task), notice: 'Task was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to character_task_path(@character, @task), notice: 'Task was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy!

    respond_to do |format|
      format.html { redirect_to character_tasks_path, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_character
    @character = Character.find(params[:character_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:name, :generate_image, :description, :character_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/characters/_character.html.erb
<div class="flex gap-10" id="<%= dom_id character %>">
  <figure class="h-80 aspect-[4/5] block ">
    <img class="h-full w-full rounded-2xl object-cover object-center" src="<%= character.image_src %>" alt="">
  </figure>
  <div class=" pt-10 flex flex-col justify-between">
    <div class="flex flex-col gap-4">
      <h2 class=" text-4xl font-semibold">
        <%= link_to character.name , character_path(character) %>
      </h2>
      <p class=" text-content2">
        <%= character.personality.truncate(1000) %>
      </p>
    </div>
    <div class="flex gap-4 mt-4">
      <%= link_to "Edit this character", edit_character_path(character), class: "btn stop-propagation" %>
      <%= button_to "Destroy this character", @character, method: :delete, class: "btn btn-error stop-propagation" %>
    </div>
  </div>
</div>

app/views/characters/_form.html.erb
<%= form_with(model: character, class: "space-y-4") do |form| %>
  <% if character.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>
      <ul>
        <% character.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-field">
    <label class="form-label">Name</label>
    <%= form.text_field :name, class: "input" %>
    <label class="form-label">
      <span class="form-label-alt">
        This will be the name of your character.
      </span>
    </label>
  </div>
  <div class="form-field">
    <label class="form-label">Personality</label>
    <%= form.text_area :personality, class: "textarea !max-w-none w-4/5 h-96" %>
    <label class="form-label">
      <span class="form-label-alt">
        Describe your character's personality as best as you can.
      </span>
    </label>
  </div>
  <div class="form-field">
    <label class="form-label">Base image</label>
    <%= form.text_field :image_src, class: "input" %>
    <label class="form-label">
      <span class="form-label-alt">
        Provide a URL to an image of your character.
      </span>
    </label>
  </div>
</div>
<%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/characters/edit.html.erb
<div class="flex gap-2 items-end">
  <h2 class="text-3xl font-semibold">
    Edit character
  </h2>
  <%= link_to "Back to character", character_path(@character), class: "link link-primary link-underline-hover" %>
</div>
<%= render "form", character: @character %>

app/views/characters/index.html.erb
<p style="color: green"><%= notice %></p>
<%= link_to "New character", new_character_path(), class: "btn btn-primary mb-4" %>
<div class=" flex flex-col gap-6">
  <%= render @characters %>
</div>

app/views/characters/new.html.erb
<div class="flex gap-2 items-end">
  <h2 class="text-3xl font-semibold">
    Create character
  </h2>
  <%= link_to "Back to characters", characters_path, class: "link link-primary link-underline-hover" %>
</div>
<%= render "form", character: @character %>

app/views/characters/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @character %>
<div class="divider"></div>
<div class=" flex flex-col gap-6">
  <div class="flex justify-between">
    <div class="flex gap-2 items-end">
      <h2 class="text-3xl font-semibold">
        Recently created tasks
      </h2>
      <%= link_to "All tasks", character_tasks_path(@character), class: "link link-primary link-underline-hover" %>
    </div>
    <%= link_to "New task", new_character_task_path(@character), class: "btn btn-primary" %>
  </div>
  <div class="grid grid-cols-3 gap-10">
    <%= render @tasks, show_buttons: false %>
  </div>
</div>
<div class="divider"></div>
<div class=" flex flex-col gap-6">
  <div class="flex gap-2 items-end">
    <h2 class="text-3xl font-semibold">
      Recent results
    </h2>
    <%= link_to "All results", character_results_path(@character), class: "link link-primary link-underline-hover" %>
  </div>
  <div class="grid grid-cols-3 gap-10">
    <%= render @results %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="light">
  <head>
    <title>Ainfluencer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>
  <body class=" container mx-auto py-10">
    <%= yield %>
  </body>
</html>

app/views/results/_form.html.erb
<%= form_with(model: [character, result]) do |form| %>
  <% if result.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(result.errors.count, "error") %> prohibited this result from being saved:</h2>
      <ul>
        <% result.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>
  <div>
    <%= form.label :image_src, style: "display: block" %>
    <%= form.text_area :image_src %>
  </div>
  <div>
    <%= form.label :task_id, style: "display: block" %>
    <%= form.text_field :task_id %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/results/_result.html.erb
<div class="min-h-40 flex flex-col gap-2 card card-body bg-transparent border" id="<%= dom_id result %>">
  <p class="font-semibold text-lg">
    <%= link_to "Result ##{result.id}", character_result_path(@character, result)  %>
  </p>
  <p class=" text-content2">
    <%= result.content.truncate(100) %>
  </p>
  <div class="w-full flex  mt-4 justify-end">
    <%= button_to "Delete", character_result_path(@character, result), method: :delete, class: "btn btn-error" %>
  </div>
</div>

app/views/results/edit.html.erb
<h1>Editing result</h1>
<%= render "form", result: @result, character: @character %>
<br>
<div>
  <%= link_to "Show this result", character_result_path(@character, @result) %> |
  <%= link_to "Back to results", character_results_path(@character) %>
</div>

app/views/results/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="flex gap-2 items-end mb-6">
  <h2 class="text-3xl font-semibold">
    Results
  </h2>
  <%= link_to "Back to character", character_path(@character), class: "link link-primary link-underline-hover" %>
</div>
<div id="tasks" class="flex flex-col gap-6">
  <% @results.each do |result| %>
    <%= render result %>
  <% end %>
</div>

app/views/results/new.html.erb
<h1>New result</h1>

<%= render "form", result: @result %>

<br>

<div>
  <%= link_to "Back to results", results_path %>
</div>

app/views/results/show.html.erb
<div class="min-h-40 flex flex-col gap-2" id="<%= dom_id @result %>">
  <div class="flex gap-2 items-end mb-2">
    <h2 class="text-3xl font-semibold">
      <%= link_to "Result ##{@result.id}", character_result_path(@character, @result)  %>
    </h2>
    <%= link_to "All results", character_results_path(@character), class: "link link-primary link-underline-hover" %>
  </div>
  <div class="flex gap-20">
    <img class=" aspect-square h-[512px]" src="<%= @result.image_src %>">
    <div class=" text-content2 inline-flex flex-col gap-4">
      <%= simple_format(@result.content) %>
    </div>
  </div>
  <div class="w-full flex  mt-4 justify-end">
    <%= button_to "Delete", character_result_path(@character, @result), method: :delete, class: "btn btn-error" %>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: [@character, @task], class: "space-y-4") do |form| %> <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class=" form-field">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "input" %>
  </div>
  <div class="form-field">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: " textarea !max-w-none w-4/5 h-96" %>
  </div>
  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/tasks/_task.html.erb
<div class="min-h-40 flex flex-col gap-2 card card-body bg-transparent border" id="<%= dom_id task %>">
  <p class="font-semibold text-lg">
    <%= link_to task.name, character_task_path(@character, task)    %>
  </p>
  <p class=" text-content2">
    <%= task.description %>
  </p>
  <div class="w-full flex  mt-4 <%= show_buttons ? "justify-between" : "justify-end" %>">
    <% if show_buttons %>
      <div class="flex gap-2">
        <%= link_to "Edit", edit_character_task_path(@character, task), class: "btn btn-secondary" %>
        <%= button_to "Delete", character_task_path(@character, task), method: :delete, class: "btn btn-error" %>
      </div>
    <% end %>
    <%= button_to "Use", character_results_path(@character), method: :post,
    params: { task_id: task },
    class: "btn btn-primary stop-propagation" %>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="flex gap-2 items-end">
  <h2 class="text-3xl font-semibold">
    Edit task
  </h2>
  <%= link_to "All tasks", character_tasks_path(@character), class: "link link-primary link-underline-hover" %>
</div>
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="flex gap-2 mb-6 justify-between">
  <div class="flex gap-2 items-end ">
    <h2 class="text-3xl font-semibold">
      Tasks
    </h2>
    <%= link_to "Back to character", character_path(@character), class: "link link-primary link-underline-hover" %>
  </div>
  <%= link_to "New task", new_character_task_path(@character), class: "btn btn-primary self-end" %>
</div>
<div id="tasks" class="flex flex-col gap-6">
  <% @tasks.each do |task| %>
    <%= render task, show_buttons: false  %>
  <% end %>
</div>

app/views/tasks/new.html.erb
<div class="flex gap-2 items-end">
  <h2 class="text-3xl font-semibold">
    Create task
  </h2>
  <%= link_to "All tasks", character_tasks_path(@character), class: "link link-primary link-underline-hover" %>
</div>
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @task, show_buttons: true  %>